ALTER TABLE users
    DROP CONSTRAINT IF EXISTS users_fk0;

ALTER TABLE matches
    DROP CONSTRAINT IF EXISTS matches_fk0;

ALTER TABLE matches
    DROP CONSTRAINT IF EXISTS matches_fk1;

ALTER TABLE matches
    DROP CONSTRAINT IF EXISTS matches_fk2;

ALTER TABLE matches
    DROP CONSTRAINT IF EXISTS matches_fk3;

ALTER TABLE bets
    DROP CONSTRAINT IF EXISTS bets_fk0;

ALTER TABLE bets
    DROP CONSTRAINT IF EXISTS bets_fk1;

ALTER TABLE bets
    DROP CONSTRAINT IF EXISTS bets_fk2;

ALTER TABLE bets
    DROP CONSTRAINT IF EXISTS bets_fk3;

ALTER TABLE results
    DROP CONSTRAINT IF EXISTS results_fk0;

ALTER TABLE results
    DROP CONSTRAINT IF EXISTS results_fk1;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS pictures;

DROP TABLE IF EXISTS sport_games;

DROP TABLE IF EXISTS matches;

DROP TABLE IF EXISTS teams;

DROP TABLE IF EXISTS bets;

DROP TABLE IF EXISTS scores;

DROP TABLE IF EXISTS results;
